name: å–‚é²¸é±¼ ğŸ³
author: Wei Jingyu
description: Just some notes.
permalink: "/:title"
collections:
  notes:
    output: true
    permalink: "/:slug"

summer: In the depths of winter I finally learned there was in me an invincible summer.
